#ifndef __databasespanel__
#define __databasespanel__

/**
@file
Subclass of DatabasesPanelBase, which is generated by wxFormBuilder.
*/

#include "mainframbase.h"

//// end generated include

/** Implementing DatabasesPanelBase */
class DatabasesPanel : public DatabasesPanelBase
{
	public:
		/** Constructor */
		DatabasesPanel( wxWindow* parent );
	//// end generated class members
	private:
		void InitTreeList();
};

#endif // __databasespanel__
