#ifndef __logindatabasedialog__
#define __logindatabasedialog__

/**
@file
Subclass of LoginDatabaseDialogBase, which is generated by wxFormBuilder.
*/

#include "mainframbase.h"

//// end generated include

/** Implementing LoginDatabaseDialogBase */
class LoginDatabaseDialog : public LoginDatabaseDialogBase
{
	public:
		/** Constructor */
		LoginDatabaseDialog( wxWindow* parent );
	//// end generated class members

};

#endif // __logindatabasedialog__
