#ifndef __mainframe__
#define __mainframe__
#include "wxincludes.h"

/**
@file
Subclass of MainFrameBase, which is generated by wxFormBuilder.
*/

#include "mainframbase.h"
#include "databasespanel.h"

//// end generated include

/** Implementing MainFrameBase */

class MainFrame : public MainFrameBase
{
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members
	private:
		void InitView();
		void InitData();
		void InitMenus();
		void WriteJson();
		void ReadJson();
	private:
		DatabasesPanel* m_dataPanel;
};

#endif // __mainframe__
